# Generated by Django 4.2.6 on 2023-10-17 23:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="vote_to_skip",
            new_name="votes_to_skip",
        ),
    ]
